name: '部屬前端專案'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/network-dashboard # 使用你的 Docker Hub 使用者名稱和應用程式名稱
      - name: 更新 known_hosts 文件 # 步驟的名稱
        run: | # 將要執行的命令
          mkdir -p ~/.ssh  # 在用戶的主目錄下創建 .ssh 目錄，如果該目錄已存在，則不會報錯
          ssh-keyscan ${{ secrets.HOST_NAME }} >> ~/.ssh/known_hosts  # 從指定的主機獲取公鑰，並將其追加到 known_hosts 文件中
      # 請將 'hostname' 替換為你的服務器地址，例如 IP 地址或域名
      - name: Deploy to Docker
        run: |
          ssh root@${{ secrets.HOST_NAME }} '
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/network-dashboard
            docker rm -f github-ac-sample || true
            docker run -d -p 80:3000 --name github-ac-sample --env-file $HOME/websample/node-env/.env ${{ secrets.DOCKER_HUB_USERNAME }}/network-dashboard
